apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helm-output.yaml
- rook-ceph-mgr-dashboard.yaml

# patches:
# - target:
#     kind: Namespace
#     name: ceph
#   patch: |-
#     - op: add
