### Encrypt this file using SOPS before you commit it with sensitive information to your git repository
apiVersion: v1
kind: Secret
metadata:
    name: dev-bb-secret
    namespace: bigbang
stringData:
    values.yaml: ENC[AES256_GCM,data:qm47vJdquXm5JzKyZ+G0LUzNb+hW+2FTADetA3XHMxWDonpCROUG6N5QjYx6eKkN8waIGAYYYwGNG/H6DDVn0lZCdqW6GJCajmcgiyJbNm+ofj78Oa0p82PUljolFPsdLJOpwZbB1YInL7Sb0W2x4yMVKbg/A4l7ue/e4bXcaQx5y3xKNYfInyYI3iKeujzY7AyYkewoFruvikHKly48f3gYds4tXkN2SSej7PYNOHv1mWGELv9domwrvoTPKMHSqJ2bPkcFy6KhMmdKY02ys0SPyTfQlRg7w9AZ92HNhV2cuZKKoTzvUitCcQskAB3sAdA+vjqXwKHPlzaoj2U2apUvJLqaNwVSlptd+W50SiTyMB+unWUU6gq9jn4TZ9sdecY27OXUihAcRGB0gFOTxODfCFrQWFNe17o9N2ZtZs+QGFhViPnXZmLbR1WG142HqaZDWBGrBE/cHe9AteU7IBYYHA0Uvb3BX9ASEbrmptaxSWj6aFu/KgGFlcLfQ4/9lhOsXvwJRPGwi39sR1cby5EIUwR5X62hkTpka1M=,iv:E/rfwyw0xaRQfw1uLpZlON9raQXQFtspmLlfqgWmPiw=,tag:xSa48A0n7bOiIRf+ztURPA==,type:str]
sops:
    lastmodified: "2026-05-12T12:27:58Z"
    mac: ENC[AES256_GCM,data:QIvQwsc7vspbVrstE73F1DiUXqI8h3Ef9wj914QV9uLiFCGUEEODNe+1GiMcmxaBECfE+njKblY/l/AUWJ+g/RZLQrmuRkoCfTXMllwhIT7vkq2XXjh6GCX9DZL7lYB4fwSeLxDbo7LNoSzUfDC59nEMW3K+NeDR0k5p9lKVx3I=,iv:ikqQxPUsupeKft5LLg0gM4I5HOtIsbyQCJs2RvjvKkg=,tag:WkecBll9Ew8u8T1IVLWJnw==,type:str]
    pgp:
        - created_at: "2026-05-12T12:27:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwGanXxWpzTxAQ/8DiHRgbSGhY+jeZ8aB3+ThyX/CAseStbgU2HzllCXIp4H
            /UMLDNfY3TqEn+9oUAPyP48l1B56nLARAFp5tbrFJ2ST7cA6kjkhjWoAVZ0FA7TR
            gVrgOCu/gTAVA3PEiliXrDjHFgEHa4asLfCHrKnB72lQr4jE7NT4qDzrBqb41+ef
            aCCTnXui2OWC5NUctqt3b89+LUBU7BgboH+gGROYN9KkYo3LEbuo+Lt9eR5F4LnC
            0gGEgnuHGwRajgSDIPameJLSjiJv8kmphEpsyIiiY3NL8OZpdZBcpTZhPDNnHcdO
            AAxJEAmiHnT36cKLm+rQowWWGP9jWK6M2vQyHFwgN/JoiwgDosgCUjbKDJrgWK/g
            109EYbTeDchi/soMgfrPBe8wOyJoijLyc/wHlQUKk/QzhynrImxsDpd4Pb9+ccVJ
            8pYJdL/GKbfskgOL2Q3WdVCAj4yEXkDaMdU2/M+BBwlFX1IDa8PFRPCHl1cFEhVL
            y1jzS9PRp/YRSvwbU/t2UegDDw3qiCGHoJpRyJ4VZcdroJy31IpTvj67D79sXCpl
            9t0dw/leLSXMXhU0jrJGvLfdc+xyZ/HXlnDOkZv2oHiltUNcfreE5UVrQ/urr2aY
            ESG86lZUgpsqRI4sD/whcibhlrwnKXXfQmNqryN+IOGhVwLOFTdGwWQYECUUrDDU
            aAEJAhD87WUNHHNZSPb9jGeIPkwRgssR7Oe4zsAVdnMCG3GL0c3r1Rw1qh/7KiLb
            Wz+iDn4gdSYq4VzJBSImzvrlJzGRfx0TcVdnWT5INBplvP38Eevj3Kav0aZEF68q
            aZGqfIh9OWUL
            =fXeS
            -----END PGP MESSAGE-----
          fp: 34A9C8BD30F32BD9A57F75B5CCB51805C7DD7D1D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
