### Encrypt this file using SOPS before you commit it with sensitive information to your git repository
apiVersion: v1
kind: Secret
metadata:
    name: dev-bb-secret
    namespace: bigbang
stringData:
    values.yaml: ENC[AES256_GCM,data:zla/m1rCvEKxGzc8wTdFqzWVKlUkRMhbenw4uXa/BJUS,iv:IpJ/bBnOCG1tqDSeweFRotUwWntQhDq2q5ierDsyrmk=,tag:D7GNjUc/EvmTw+GjP6ckSw==,type:str]
sops:
    lastmodified: "2026-05-07T14:08:15Z"
    mac: ENC[AES256_GCM,data:F3B/3gitDrR6eNbki62S2zWC4T+K4B5NzgeJvC7STfLJiQoPELu9n538PIBXk+MUdUe8xZrle/geisTTccfJB+E8LcOSWNhFPkRd45BSIwS7pnXl4v6rA2sDrRQrGS+qvWxsPYNnCgR+QpOIEVQEImp5Smw7s2nwm0lphoTxGq0=,iv:iUFFNhapymuIvrRjAqD82vOoziShPQZIVLwtLTqj7dI=,tag:z1kFTjhD5tomi4rY2rLVSw==,type:str]
    pgp:
        - created_at: "2026-05-07T14:08:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwGanXxWpzTxARAAliCqtYHvuidgggXrfwRnf+P2fQIfPMQ9meB2hk/r5dx2
            ilBgulFCf7Fo7HA/4YVDfceHP2mkEMBAJAlWU8t0LuRgE/GfD3aAHlSy/w4eV5eE
            aDxEv28dk9m1Aq0260CltN4dEEvDVnNBSv2IH91DWIYX3DK/2q7D0Fjq8Ba4j5Wk
            TjWaHxWD7YEKMs808sL2yT5wx1VYPHyPtpJMyFf7N1X3Lv1qEKoj8L0wfST6ThhL
            EkUB5RzcTSnIUJYnKI/8UR8NuySRjGCp+CFctWf0eOtuN1Ijz+8Q59DVKr8YmQ/c
            8OxyIq8qxMvqgUU7oFb8l3X+eg3j8cePhI7HSxR5jIVXwtURHjOJM97nJVzD4bQ2
            fbf4WywFdEG7WcNh4SsLJgwpjFAQk9XDGbD2kHHQX1/DEJnVhMwIIzTQh9OHct0X
            b8EqxPLCixFdV3HhQqAlCiLJRb7jULgt/VefcZ/q0kmKAXm9RWHU+zlNrH2UCrGN
            8OwcmWkxDHBATJs525EtnFcd7hPnqa8nO0P42nbYBgyyl74hCtFhJQyo9ozGO1R0
            X5R0nII9lW6RxmSYJruF8OKMhT0hUNSwCNubOBaYi7DojpbZKGBJREmCTPX96ycd
            j6d8IRzUoQtwQWX30/ME1kAGjUQ45lIcqWRTPoAYF0KCSGsbo+wxn/t1cJMdUFrU
            aAEJAhBveafjgdFLndhENiR7/o4ovD8iAOZ3ivgKczR6FG+49HbsReXx6C0UwI3r
            Nr8A1BPpDdF+LcuBFS2gwpKuOgK1oIPotLr8KClILMBRRrQFn6bIT5fCbbTH25K1
            JCDfXxwfXhhn
            =nmui
            -----END PGP MESSAGE-----
          fp: 34A9C8BD30F32BD9A57F75B5CCB51805C7DD7D1D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
