apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debug-allow-all
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: netshoot
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
